on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH }}
        repository: manjaro-sway/packages
        event-type: package_update
        client-payload: '{ "repository": "${{ github.repository }}", "sha": "${{ github.sha }}"}'
