name: trigger pkgbuild

on:
  release:
    types: [published]  
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to dispatch'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
    -
      name: get md5
      run: |
        curl --location --remote-header-name --silent -o release.tar.gz \
          https://github.com/${{ github.repository }}/archive/${{ github.event.release.tag_name || github.event.inputs.tag }}.tar.gz
        echo "MD5=$(md5sum release.tar.gz | cut -d ' ' -f 1)" >>$GITHUB_ENV 
    - 
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH }}
        repository: manjaro-sway/manjaro-sway-settings
        event-type: source_update
        client-payload: '{ "repository": "${{ github.repository }}", "version": "${{ github.event.release.tag_name || github.event.inputs.tag }}", "md5": "${{ env.MD5 }}" }'
